spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:database
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

admin.password-hash=$2a$10$bdkKm/hsSib.K8oKNY2PLuKsd092HNTYDL98lfFbxU5W21iWYvRxa

jwt.secret=roomescape-jwt-secret-key-must-be-at-least-32-bytes-long
jwt.expiration-millis=7200000
